import assert from 'node:assert/strict';
import fs from 'node:fs';
import {prepareCircuit,createFlight,advance,fly,newWeights,Trainer} from '../dist/engine.js';
const raw=JSON.parse(fs.readFileSync(new URL('../dist/assets/circuit.json',import.meta.url)));
const c=prepareCircuit(raw),graduate=JSON.parse(fs.readFileSync(new URL('../dist/assets/graduate.json',import.meta.url)));
assert.equal(c.n,96);assert.equal(c.edges.length,3199);assert.equal(c.edges.reduce((s,e)=>s+e[2],0),85785);
assert.equal(new Set(c.neurons.map(n=>n.id)).size,96);
assert(c.edges.every(([src,dst,,sign])=>src>=0&&src<96&&dst>=0&&dst<96&&[-1,1].includes(sign)));
const flight=fly(c,graduate.weights,440001,1);
assert.deepEqual(flight,fly(c,graduate.weights,440001,1),'A checkpoint and seed must reproduce the same flight');
assert(Number.isFinite(flight.reward));assert(flight.done);
const empty=createFlight(4,0);empty.fuel=0;const vy=empty.vy;advance(empty,[1,0,0]);assert.equal(empty.throttle,0);assert(empty.vy<vy,'Fuel exhaustion must remove thrust');
const unsafe=createFlight(5,0);unsafe.y=8.01;unsafe.vy=-8;unsafe.angle=.5;advance(unsafe,[-1,0,0]);assert(unsafe.done);assert(!unsafe.landed,'An unsafe touchdown must not count as a landing');
const trainer=new Trainer(raw);const initial=[...trainer.weights];const result=trainer.trainGeneration(6,2);
assert.equal(result.episodes,28);assert.equal(trainer.generation,1);assert(trainer.weights.every(Number.isFinite));
assert(graduate.weights.slice(27).some((v,i)=>v!==newWeights()[27+i]),'Training must change gains on the actual retained edges');
const html=fs.readFileSync(new URL('../dist/index.html',import.meta.url),'utf8');
for(const m of html.matchAll(/(?:src|href)="([^"#]+)"/g))if(!/^(https?:|data:|\.\/)/.test(m[1]))assert(fs.existsSync(new URL('../dist/'+m[1],import.meta.url)),`Missing asset ${m[1]}`);
console.log(JSON.stringify({checks:'passed',neurons:c.n,connections:c.edges.length,replay:{seed:440001,scenario:1,landed:flight.landed},trainingBatch:result.episodes}));
