import fs from 'node:fs';
import {Worker,isMainThread,parentPort,workerData} from 'node:worker_threads';
import {createHash} from 'node:crypto';
import {SCENARIOS} from '../dist/missions.js';
import {loadFullNetwork} from './full-network-node.mjs';
import {rollout,flightResult} from '../dist/full-controller.js';
const files={center:'full-pilot',degraded:'full-specialist',out:'full-expert',orbital:'full-orbital'},hash=w=>createHash('sha256').update(Buffer.from(Float64Array.from(w).buffer)).digest('hex');
if(isMainThread){
 const checkpoints=Object.fromEntries(Object.entries(files).map(([family,name])=>[family,JSON.parse(fs.readFileSync(`dist/assets/${name}.json`))])),hashes=Object.fromEntries(Object.entries(checkpoints).map(([family,c])=>[family,hash(c.weights)])),cases=[],flights=[],seeds=[723611,729727],profiles=[0,1,6,7,24,26],gains=[1,1.02,1.05],started=Date.now();
 for(let i=0;i<seeds.length;i++)for(const scenario of profiles)for(const gain of gains)cases.push({seed:seeds[i],scenario,gain,variability:i===0?0:.4});let next=0,active=0;
 await new Promise((resolve,reject)=>{for(let i=0;i<2;i++){const worker=new Worker(new URL(import.meta.url),{workerData:{checkpoints}});active++;const dispatch=()=>{if(next<cases.length)worker.postMessage(cases[next++]);else{worker.postMessage(null);if(--active===0)resolve();}};worker.on('error',reject);worker.on('message',f=>{flights.push(f);console.log(JSON.stringify({completed:flights.length,total:cases.length,gain:f.activationGain,scenario:f.scenario,landed:f.landed,reason:f.reason,seconds:Math.round((Date.now()-started)/1000)}));dispatch();});dispatch();}});
 const summary=gains.map(gain=>{const f=flights.filter(f=>f.activationGain===gain);return{gain,landings:f.filter(f=>f.landed).length,episodes:f.length,meanReward:f.reduce((n,s)=>n+s.score,0)/f.length,styles:f.filter(f=>f.styleBonus>0).length};});
 const report={controller:'malecns-full-rate-v2',sensorSchema:'flight-senses-46-v1',hashes,seeds,profiles,summary,flights,method:'Paired full-network operational experiment. Same readout weights and initial conditions; only the gain applied before each neuron activation changes. One nominal and one randomized seed per profile.',limitations:['Twelve flights per gain across six profiles are a small exploratory sample.','No retraining between gain conditions. This does not test learning speed or a biological stimulant.','The global gain rule is an authored abstraction; chemical concentrations, receptors and cell-specific octopamine effects are not modeled.'],sources:[{title:'Octopamine neurons mediate flight-induced modulation of visual processing in Drosophila',url:'https://pubmed.ncbi.nlm.nih.gov/23142045/'},{title:'Dopamine-mediated interactions between short- and long-term memory dynamics',url:'https://www.nature.com/articles/s41586-024-07819-w'}],seconds:Math.round((Date.now()-started)/1000)};fs.writeFileSync('/tmp/fly-v8/arousal-experiment.json',JSON.stringify(report,null,2));console.log(JSON.stringify({complete:true,summary,seconds:report.seconds}));
}else{
 const net=loadFullNetwork();parentPort.on('message',task=>{if(!task){parentPort.close();return;}const {scenario,seed,variability,gain}=task,weights=workerData.checkpoints[SCENARIOS[scenario].family].weights;let last;for(const s of rollout(net,weights,seed,scenario,true,variability,gain))last=s;parentPort.postMessage({...flightResult(last),variability});});
}
