import fs from 'node:fs';
import {createHash} from 'node:crypto';
const evaluation=JSON.parse(fs.readFileSync('/tmp/fly-full/evaluation.json')),recoveryOnly=JSON.parse(fs.readFileSync('/tmp/fly-full/recovery-only.json'));
const names=['full-pilot','full-specialist','full-expert'];
const checkpoints=names.map((name,i)=>{
 const file=`dist/assets/${name}.json`,c=JSON.parse(fs.readFileSync(file)),flights=evaluation.flights.filter(f=>i===0?f.scenario<6:f.scenario===i+5);
 c.evaluation={landings:flights.filter(f=>f.landed).length,episodes:flights.length,styles:flights.filter(f=>f.styleBonus>0).length,missions:[...new Set(flights.map(f=>f.scenario))],styleEnabled:true};fs.writeFileSync(file,JSON.stringify(c));
 return{name,initialization:c.initialization,generation:c.generation,completeGraphTrainingFlights:c.episodes,history:c.history,weightSHA256:createHash('sha256').update(Buffer.from(new Float64Array(c.weights).buffer)).digest('hex'),evaluation:c.evaluation};
});
const report={controller:'malecns-full-rate-v1',generatedAt:new Date().toISOString(),neurons:166700,edges:25582938,synapticContacts:124177617,sensoryCells:17937,readoutCells:2129,trainableReadoutWeights:21300,graphPassesPerDecision:2,physicsStepsPerDecision:3,physicsStepSeconds:.05,graphIndividualWeightsTrained:false,trainingAlgorithm:'Paired random perturbations of all readout weights; complete graph rollouts; lexicographic landing count then mean shaped reward.',perturbationLineage:{fullPilot:'0.12 for generations 1–3; 0.015 for 4–5',fullSpecialist:'0.12 for generation 1; 0.015 for 2',fullExpert:'0.12 for generation 1; 0.015 for 2'},checkpoints,evaluation,recoveryOnly,checks:['Independent graph-row calculations and counts','Causal command effect from a sensory neuron outside historical 96','Exact complete-graph replay and restoration of live state','Recovery-gated, capped style reward; crash/low-turn/oscillation rejection','All ten actuator mappings and stale instrument memory','Browser full-network landing with recovered turn','Browser local training completed a generation and stopped'],limitations:['24 style-enabled flights on three seeds shared across eight scenarios are a finite simulator evaluation, not a reliability guarantee.','Night and engine-fault missions remain unreliable; all failures are included.','Supervised transfer from historical landing policies and a yaw-target demonstrator initialized the readouts; this is not learning from scratch.','Individual biological edge counts and signs are fixed; only the output readouts are optimized.','This is an engineered signed rate model, not a validated biological fly emulation.']};
fs.writeFileSync('dist/assets/full-pilot-report.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({landings:evaluation.landings,episodes:evaluation.episodes,styles:evaluation.styles,trainingFlights:checkpoints.reduce((n,c)=>n+c.completeGraphTrainingFlights,0)}));
